//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class breed
    {
        public int id_breed { get; set; }
        public string namebreed { get; set; }
        public int id_typeanimal { get; set; }
    
        public virtual typeanimal typeanimal { get; set; }
    }
}
