//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usedmedicines
    {
        public int id_usedmedicines { get; set; }
        public int usedquantity { get; set; }
        public System.DateTime usagedate { get; set; }
        public int id_medicines { get; set; }
        public int id_contract { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual medicines medicines { get; set; }
    }
}
